services:
  - type: web
    name: mentorship-app
    env: python
    workingDir: backend
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://vishakhaprajapati0502:eO9B5FgM9bbmsOng@cluster0.erqciks.mongodb.net/
